baseurl = "https://hnakamur.github.io/blog/"
languageCode = "ja-jp"
title =  "hnakamur's blog"
theme =  "hn-hyde"
hasCJKLanguage = true
pygmentsUseClasses=true
assets = "content/files"
googleAnalytics = "G-KMMXGG2Z56"
staticDir = "static"

[params]
  author = "Hiroaki Nakamura"
  author_link = "https://hnakamur.github.io"
  description = "my tech memo"

[menus]
  [[menus.main]]
    name = "blog home"
    url = "https://hnakamur.github.io/blog/"

  [[menus.main]]
    name = "github @hnakamur"
    url = "https://github.com/hnakamur"

  [[menus.main]]
    name = "twitter @hnakamur2"
    url = "https://twitter.com/hnakamur2"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
