baseurl = "https://hnakamur.github.io/blog/"
languageCode = "ja-jp"
title =  "hnakamur's blog"
theme =  "hn-hyde"
hasCJKLanguage = true
pygmentsUseClasses=true
assets = "content/files"
googleAnalytics = "UA-53263855-1"

[params]
  author = "Hiroaki Nakamura"
  author_link = "https://hnakamur.github.io"
  description = "my tech memo"

[menus]
  [[menus.main]]
    name = "blog home"
    url = "https://hnakamur.github.io/blog/"

  [[menus.main]]
    name = "github @hnakamur"
    url = "https://github.com/hnakamur"

  [[menus.main]]
    name = "twitter @hnakamur2"
    url = "https://twitter.com/hnakamur2"

[permalinks]
  post = "/content/post/:year/:month/:day/:filename/"
