baseurl = "https://hnakamur.github.io/blog/"
languageCode = "ja-JP"
title =  "hnakamur's blog at github"
theme =  "liquorice-hn"
pygmentscodefences = true
pygmentsstyle = "github"

[params]
  subtitle = "my trial and error log"
  author = "Hiroaki Nakamura"
  author_link = "https://hnakamur.github.io"
  gaid = "UA-53263855-1"
  # syntax_highlight = "prism.js"

[permalinks]
  post = "/:year/:month/:day/:filename/"
