baseurl = "/blog/"
languageCode = "ja-JP"
title =  "hnakamur's blog at github"

[params]
  subtitle = "my trial and error log"
  author = "Hiroaki Nakamura"
  gaid = "UA-53263855-1"
  ad_client = "ca-pub-6617520246100499"
  ad_slot = "7104419366"

[permalinks]
  post = "/:year/:month/:day/:filename/"
