baseurl = "/blog/"
languageCode = "ja-JP"
title =  "hnakamur's blog at github"
theme =  "liquorice-hn"

[params]
  subtitle = "my trial and error log"
  author = "Hiroaki Nakamura"
  gaid = "UA-53263855-1"

[permalinks]
  post = "/:year/:month/:day/:filename/"
