baseurl = "https://hnakamur.github.io/blog/"
languageCode = "ja-JP"
title =  "hnakamur's blog at github"
theme =  "hn-hyde"
hasCJKLanguage = true
#pygmentscodefences = true
#pygmentsstyle = "github"
pygmentsUseClasses=true
assets = "content/files"

[params]
  subtitle = "my trial and error log"
  author = "Hiroaki Nakamura"
  author_link = "https://hnakamur.github.io"
  gaid = "UA-53263855-1"
  description = "my tech memo"
  # syntax_highlight = "prism.js"

[permalinks]
  post = "/content/post/:year/:month/:day/:filename/"
