author = "Hiroaki Nakamura"
description = "Liquorice-hn is a small black and white theme for Hugo, based on Liquorice by Markus Eliasson."
license = "MIT"
name = "liquorice-hn"
source_repo = "http://github.com/hnakamur/liquorice-hn"
tags = ["", ""]
